mini/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('real_estate.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

real_estate/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save


class User(AbstractUser):
    is_customer = models.BooleanField(default=False)
    is_agent = models.BooleanField(default=False)
    first_name = models.CharField(max_length=100, default='')
    last_name = models.CharField(max_length=100, default='')
    email = models.EmailField()


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True)
    c_mobile = models.IntegerField(default=0)
    c_address = models.CharField(max_length=200, default='')

    def __str__(self):
        return self.user.username


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True)
    a_mobile = models.IntegerField(default=0)
    a_address = models.CharField(max_length=200, default='')
    a_company_name = models.CharField(max_length=30, default='')
    a_company_address = models.CharField(max_length=500,  default='')
    a_company_mobile = models.IntegerField( default=0)
    a_company_email = models.EmailField( default='')
    a_dis = models.CharField(max_length=500,  default='No description is added')
    a_image = models.FileField(upload_to='images/', null=True, verbose_name="", default='agent-4.jpg')

    def __str__(self):
        return self.user.username


# Property Details
class Property(models.Model):
    # objects = None
    agent = models.ForeignKey(User, on_delete=models.CASCADE)

    type = models.CharField(max_length=100,default='')
    status = models.CharField(max_length=100 , default='')
    description = models.CharField(max_length=500,default='')
    name = models.CharField(max_length=100,default='')
    address = models.CharField(max_length=200,default='')
    area = models.IntegerField(default=0)
    bathroom = models.IntegerField(default=0)
    bedroom = models.IntegerField(default=0)
    masterroom = models.BooleanField("masterroom",default=False,null=True,blank=True)
    balcony = models.BooleanField("balcony", default=False,null=True,blank=True)
    parking = models.BooleanField("parking", default=False,null=True,blank=True)
    lift = models.BooleanField("lift", default=False,null=True,blank=True)
    storeroom = models.BooleanField("storeroom", default=False,null=True,blank=True)
    swimming = models.BooleanField("swimming", default=False,null=True,blank=True)
    builder = models.CharField(max_length=100,default='')
    price = models.IntegerField(default=0)
    image = models.FileField(upload_to='images/', null=True, verbose_name="", default='')

    def __str__(self):
        return self.name


class Afeedback(models.Model):
    subject=models.CharField(max_length=100, default='')
    description= models.TextField( default='')

    def __str__(self):
        return self.subject


class Ufeedback(models.Model):
    subject=models.CharField(max_length=100, default='')
    description=models.TextField( default='')

    def __str__(self):
            return self.subject


class PropertyImage(models.Model):
    property = models.ForeignKey(Property, default=None, on_delete=models.CASCADE)
    images = models.FileField(upload_to = 'images/', null=True, blank=True)

    def __str__(self):
        return self.property.name


class Comments_model(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default='')
    u_email = models.EmailField(max_length=100, default='')
    comments = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.name

templates/a_notification.html
{% extends 'agent_dashboard.html'%}
{% load static%}
class= "{%block nav4%} active {%endblock%}
{%block main%}
<section id="main-content">
  <section class="wrapper">
    <div class="row">
      <div class="form-panel">
        <!-- MAIN CONTENT -->
        <h4 class="text-center alert alert-info">  Notification</h4>
        
        {% if info %}
        <table class="table table-hover">
          <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Comments </th>
          </tr>
          </thead>
          <tbody>
          {% for s in info %}
          <tr>
            <th scope="row">{{s.type}}</th>
            <td>{{s.name}}</td>
            <td>{{s.u_email}}</td>
            <td>{{s.comments}}</td>
            <td>
              <a href="{% url 'delete1' s.id %}" class="btn btn-danger btn-xs" style="width:45%"><i class="fa fa-trash-o "></i></a>
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
        {% else %}
        <h4>No Notifications</h4>
        {% endif %}
        <!-- END MAIN CONTENT -->
      </div>
    </div>
  </section>
</section>
{%endblock%}

templates/agent_register.html
{% extends 'base1.html'%}

{% load widget_tweaks %}
{% load static%}
{% block nav6%} active{%endblock%}
{% block body%}
<!--/ Carousel Star /-->
<div class="intro intro-carousel">
    <div id="carousel" class="owl-carousel owl-theme">
        <div class="carousel-item-a intro-item bg-image" style="background-image: url({% static 'img/slide-1.jpg'%})">
            <div class="overlay overlay-a"></div>
            <div class="intro-content display-table">
                <div class="table-cell">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="intro-body">
                                    <p class="intro-title-top">Bandra,Mumbai
                                        <br> 78345</p>
                                    <h1 class="intro-title mb-4">
                                        <span class="color-b">09 </span> Sweet Home
                                        <br> Bandra Street Market</h1>
                                    <p class="intro-subtitle intro-price">
                                        <a href="#"><span class="price-a">rent | Rs 30,000</span></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel-item-a intro-item bg-image" style="background-image: url({% static 'img/slide-2.jpg'%})">
            <div class="overlay overlay-a"></div>
            <div class="intro-content display-table">
                <div class="table-cell">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="intro-body">
                                    <p class="intro-title-top">Karol Bagh, Delhi
                                        <br> 85345</p>
                                    <h1 class="intro-title mb-4">
                                        <span class="color-b">104 </span> Shanti Vihar
                                        <br> Karol Bagh Market </h1>
                                    <p class="intro-subtitle intro-price">
                                        <a href="#"><span class="price-a">Sell | Rs 1,50,00,000</span></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel-item-a intro-item bg-image" style="background-image: url({% static 'img/slide-3.jpg'%})">
            <div class="overlay overlay-a"></div>
            <div class="intro-content display-table">
                <div class="table-cell">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="intro-body">
                                    <p class="intro-title-top">Johari Bazzar, Jaipur
                                        <br> 90045</p>
                                    <h1 class="intro-title mb-4">
                                        <span class="color-b">04 </span> Om Palace
                                        <br> Badi Chaupat Street</h1>
                                    <p class="intro-subtitle intro-price">
                                        <a href="#"><span class="price-a">rent | Rs 20,000</span></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!--/ Carousel end /-->

<div class="container mb-3 py-4">
    <h1 class="text-center">Register as Agent</h1>
    <form  method="POST" >
        {% csrf_token %}
        <div class="form-group">
            <label>UserName</label>
            {{form.username}}
        </div>

        <div class="form-group">
            <label>Password</label>
            {{form.password1}}
            <ul id="info" style="display: none">
                <li>Password must contain at least 8 characters</li>
                <li> Password must contain a special character and a capital letter</li>
                <li> Password should not be entirely numeric </li>
            </ul>
        </div>

        <div class="form-group">
            <label>Confirm Password</label>
                        {{form.password2}}
        </div>

        <div class="form-group">
            <label>First Name</label>
                        {{form.first_name}}
        </div>

        <div class="form-group">
            <label> Last Name</label>
            {{form.last_name}}
        </div>

        <div class="form-group">
            <label>Agent's Email</label>
            {{form.email}}
        </div>
<!--        <div class="form-group">-->
<!--            <label for="id_a_address"> Agent's Address</label>-->
<!--                                                {{form.a_address}}-->

<!--        </div>-->
<!--        <div class="form-group">-->
<!--            <label for="id_a_company_name">Company Name</label>-->
<!--                                                {{form.a_company_name}}-->
<!--        </div>-->
<!--        <div class="form-group">-->
<!--            <label for="a_company_address">Company Address</label>-->
<!--                                                {{form.a_company_address}}-->
<!--        </div>-->
<!--        <div class="form-group">-->
<!--            <label for="id_a_mobile">Agent's Contact</label>-->
<!--            <input type="number" maxlength="10" class="form-control" id="id_a_mobile" name="a_mobile" required>-->
<!--        </div>-->
<!--        <div class="form-group">-->
<!--            <label for="id_a_company_mobile">Company Mobile No.</label>-->
<!--            <input type="number" maxlength="10" class="form-control" id="id_a_company_mobile" name="a_company_mobile" >-->
<!--        </div>-->

<!--        <div class="form-group">-->
<!--            <label for="id_a_company_email">Company's Email</label>-->
<!--                                                            {{form.a_company_email}}-->

<!--        </div>-->
        <div style="margin-left: 500px;">
            <button class="btn btn-primary btn-lg" type="submit">Register</button>
        </div>
    </form>
</div>


{% endblock%}

templates/update_property.html
{% extends 'agent_dashboard.html'%}
<!--{% load static%}-->

{% block main%}
<!--main content start-->
<div style="margin-left:10%; width:115%">
  <section id="main-content">
      <section class="wrapper">
        <!-- /row -->
        <div class="col-lg-8">
        <div class="row mt">
          <div class="col-lg-12">
            <div class="form-panel">
              <h3 style="color:#000000">Update Property Details</h3>
              <div class="form">
                 <div class="qwe">
                <form class="cmxform form-horizontal style-form" method="POST" enctype="multipart/form-data">
                    {% csrf_token%}
                  <div class="form-group ">
                    <label for="id_name" class="control-label col-lg-2">Property Name</label>
                    <div class="col-lg-6">
                      <input class=" form-control" id="id_name" name="name" type="text" value="{{form2.name}}" />
                    </div>
                  </div>
                  <div class="form-group ">
                      <label for="id_type" class="control-label col-lg-2">Property Type</label>
                      <div class="col-lg-6">
                        <input class=" form-control" id="id_type" name="type" type="text" value="{{form2.type}}"/>
                      </div>
                    </div>
                    <div class="form-group ">
                      <label for="id_status" class="control-label col-lg-2">Property Status</label>
                      <div class="col-lg-6">
                        <input class=" form-control" id="id_status" name="status" type="text" value="{{form2.status}}"/>
                      </div>
                    </div>

                  <div class="form-group ">
                    <label for="id_address" class="control-label col-lg-2">Address</label>
                    <div class="col-lg-8">
                      <input class="form-control " id="id_address" name="address" type="text" value="{{form2.address}}"/>
                    </div>
                  </div>
                  <div class="form-group ">
                    <label for="id_area" class="control-label col-lg-2">Area</label>
                    <div class="col-lg-6">
                      <input class="form-control " id="id_area" name="area" type="number" value="{{form2.area}}" />
                    </div>
                  </div>
                  <div class="form-group ">
                    <label for="id_bathroom" class="control-label col-lg-2">Bathroom</label>
                    <div class="col-lg-6">
                      <input class="form-control " id="id_bathroom" name="bathroom" type="number" value="{{form2.bathroom}}" />
                    </div>
                  </div>
                  <div class="form-group ">
                    <label for="id_bedroom" class="control-label col-lg-2">Bedroom</label>
                    <div class="col-lg-6">
                      <input class="form-control " id="id_bedroom" name="bedroom" type="number" value="{{form2.bedroom}}"/>
                    </div>
                  </div>
                  <div class="form-group ">
                    <div class="col-lg-10">
                        <input type="checkbox" id="id_balcony" name="balcony"/>&nbsp;&nbsp;
                        <label for="id_balcony" >Balcony</label>
                      </div>
                      <div class="col-lg-10">

                        <input type="checkbox"  id="id_storeroom" name="storeroom"/>
                        <label for="id_storeroom">Storeroom</label>
                      </div>
                      <div class="col-lg-10">

                        <input type="checkbox"  id="id_parking" name="parking"/>
                        <label for="id_parking">Parking</label>
                      </div>
                      <div class="col-lg-10">

                        <input type="checkbox"  id="id_swimming" name="swimming"/>
                        <label for="id_swimming">Swimming</label>
                      </div>
                      <div class="col-lg-10">

                        <input type="checkbox"  id="id_masterroom" name="masterroom"/>
                        <label for="id_masterroom">Masterroom</label>
                      </div>
                      <div class="col-lg-10">

                        <input type="checkbox"  id="id_lift" name="lift"/>
                        <label for="id_lift">Lift</label>
                      </div>

                  </div>
                  <div class="form-group ">
                    <label for="id_builder" class="control-label col-lg-2">Builder Name</label>
                    <div class="col-lg-6">
                      <input class="form-control " id="id_builder" name="builder" type="text" value="{{form2.builder}}"/>
                    </div>
                  </div>
                  <div class="form-group ">
                      <label for="id_price" class="control-label col-lg-2">price</label>
                      <div class="col-lg-6">
                        <input class="form-control " id="id_price" name="price" type="number" value="{{form2.price}}"/>
                      </div>
                    </div>
                    <!--                    <div class="form-group ">-->
                    <!--                      <label for="id_title" class="control-label col-lg-2">Title</label>-->
                    <!--                      <div class="col-lg-6">-->
                    <!--                        <input class="form-control " id="id_title" name="title" type="text" />-->
                    <!--                      </div>-->
                    <!--                    </div>-->
                    <!--                    <div class="form-group ">-->
                    <!--                      <label for="id_description" class="control-label col-lg-2">description</label>-->
                    <!--                      <div class="col-lg-6">-->
                    <!--                        <input class="form-control " id="id_description" name="description" type="text" />-->
                    <!--                      </div>-->
                    <!--                    </div>-->
                    <div class="form-group ">
                      <label for="id_description" class="control-label col-lg-2">Property Description</label>
                      <div class="col-lg-6">
                        <input class=" form-control" id="id_description" name="description" type="text" value="{{form2.description}}"/>
                      </div>
                    </div>
                    <div class="form-group ">
                      <label for="id_image" class="control-label col-lg-2">Image</label>
                      <div class="col-lg-6">
                        <input class="form-control " id="id_image" name="image" type="file" value="{{form2.image}}"/>
                      </div>
                    </div>
                  <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                      <button class="btn btn-primary" type="submit">Update</button>
                      <button class="btn btn-theme04" type="button">Cancel</button>
                    </div>
                  </div>
                </form>
                 </div>
              </div>
            </div>
            <!-- /form-panel -->
          </div></div>

          <!-- /col-lg-12 -->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>
  </div>


{%endblock%}

templates/view_agent.html
{% extends 'agent_dashboard.html'%}
<!--{% load static%}-->
{%block nav1%} active
{%endblock%}
{% block main%}
<!--main content start--><!--main content start-->
<section id="main-content">
    <section class="wrapper site-min-height">
        <div class="row mt">
            <div class="col-lg-12">
                <div class="row content-panel">

                    <!-- /col-md-4 -->
                    <div class="col-md-4 profile-text">
                        <h3>{{user.username}}</h3>
                        {% if user.is_agent == True%}
                        <h6> Agent</h6>
                                                            {% endif %}

                        <p>{{user.agent.a_dis}}</p>
                        <br>

                    </div>
                    <!-- /col-md-4 -->
                    <div class="col-md-4 centered">
                        <div class="profile-pic">
<!--                            {% if user.agent.a_image %}-->
                                <p><img src="{{user.agent.a_image.url}}" class="img-circle"></p>
<!--                            {% else %}-->
<!--                                <p><img src="{% static 'dashboard/img/ui-sam.jpg'%}" class="img-circle"></p>-->
<!--                            {% endif %}-->
                            </div>
                    </div>
                    <!-- /col-md-4 -->
                </div>
                <!-- /row -->
            </div>

            <!-- /col-lg-12 -->
            <div class="col-lg-12 mt">
                <div class="row content-panel">
                    <div class="panel-heading">
                        <ul class="nav nav-tabs nav-justified">
<!--                            <li class="active">-->
<!--                                <a data-toggle="tab" href="#overview">Overview</a>-->
<!--                            </li>-->
                            <li>
                                <a data-toggle="tab" href="#contact" class="contact-map">Contact</a>
                            </li>
                            <li>
                                <a data-toggle="tab" href="#edit">Edit Profile</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /panel-heading -->
                    <div class="panel-body">
                        <div class="tab-content">
                            <!-- /tab-pane -->
                            <div id="contact"  class="tab-pane active">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div id="map">
                                            <div class="s-12 grayscale center">
                                                <iframe src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=lalbagh%20burhanpur+(My%20Business%20Name)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed" width="100%" height="450" frameborder="0" style="border:0"></iframe>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /col-md-6 -->
                                    <div class="col-md-6 detailed">
                                        <h4>Location</h4>
                                        <div class="col-md-8 col-md-offset-2 mt">
                                            <p>
                                                <b>My Address<br/></b>{{user.agent.a_address}}.<br/>
                                                <b>Company Address<br/></b>{{user.agent.a_company_address}}.<br/>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-md-6 detailed">
                                         <h4>Contacts</h4>
                                        <div class="col-md-8 col-md-offset-2 mt">
                                            <p>
                                                <b>My Contact <br/></b>{{user.agent.a_mobile}}.<br/>
                                                <b>Company Contact<br/></b>{{user.agent.a_company_mobile}}.<br/>
                                            </p>
                                            <br>
                                            <p>
                                                <b>My Email<br/></b>{{user.email}}.<br/>
                                                <b>Company Email<br/></b>{{user.agent.a_company_email}}.<br/>
                                            </p>
                                        </div>
                                    </div>
                                    <!-- /col-md-6 -->
                                </div>
                                <!-- /row -->
                            </div>
                            <!-- /tab-pane -->
                            <div id="edit" class="tab-pane">
                                <div class="row">
                                    <div class="col-lg-8 col-lg-offset-2 detailed">
                                        <h4 class="mb">Personal Information</h4>

                                        <form class="form-horizontal" method="POST" enctype="multipart/form-data">
                                            {% csrf_token%}
                                            <!--                                      {{form1.as_p}}-->
                                            <div class="form-group">
                                                <label class="col-lg-2 control-label"> Photo</label>
                                                <div class="col-lg-6">
                                                    <input type="file" id="id_a_image" value="{{user.agent.a_image.url}}" name='a_image' class="file-pos" required>
                                                    <!--                                                    {{user.agent.a_image.url}}-->

                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-2 control-label">Mobile</label>
                                                <div class="col-lg-6">
                                                    <input type="text" placeholder=" " id="id_a_mobile" name='a_mobile'
                                                           class="form-control" value="{{user.agent.a_mobile}}">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-2 control-label">Address</label>
                                                <div class="col-lg-6">
                                                    <input type="text" placeholder=" " id="id_a_address"
                                                           name='a_address' class="form-control"
                                                           value="{{user.agent.a_address}}">
                                                </div>
                                            </div>
                                            <!--                  </div>-->
                                            <!--                      <div class="col-lg-8 col-lg-offset-2 detailed ">-->
                                        <br> <h4 class="mb">Company Information</h4>
                                            <div class="form-group">
                                                <label class="col-lg-2 control-label">Name</label>
                                                <div class="col-lg-6">
                                                    <input type="text" placeholder=" " id="id_a_company_name"
                                                           name='a_company_name' class="form-control"
                                                           value="{{user.agent.a_company_name}}">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-2 control-label">Address</label>
                                                <div class="col-lg-6">
                                                    <input type="text" placeholder=" " id="id_a_company_address"
                                                           name='a_company_address' class="form-control"
                                                           value="{{user.agent.a_company_address}}">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-2 control-label">Phone</label>
                                                <div class="col-lg-6">
                                                    <input type="text" placeholder=" " id="id_a_company_mobile"
                                                           name='a_company_mobile' class="form-control"
                                                           value="{{user.agent.a_company_mobile}}">
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="col-lg-2 control-label">Email</label>
                                                <div class="col-lg-6">
                                                    <input type="text" placeholder=" " id="id_a_company_email"
                                                           name='a_company_email' class="form-control"
                                                           value="{{user.agent.a_company_email}}">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-2 control-label">Description</label>
                                                <div class="col-lg-6">
                                                    <input type="text" placeholder=" " id="id_a_dis"
                                                           name='a_dis' class="form-control"
                                                           value="{{user.agent.a_dis}}">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="col-lg-offset-2 col-lg-10">
                                                    <button class="btn btn-theme" type="submit">Save</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                    <!-- /col-lg-8 -->
                                </div>
                                <!-- /row -->
                            </div>
                            <!-- /tab-pane -->
                        </div>
                        <!-- /tab-content -->
                    </div>
                    <!-- /panel-body -->
                </div>
                <!-- /col-lg-12 -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </section>
    <!-- /wrapper -->
</section>
<!-- /MAIN CONTENT -->
<!--main content end-->


{%endblock%}